# ============================================================
# WT Studio
# Version : 0.1.0
#
# File:
# pbr_converter.py
#
# Description:
# Converts War Thunder textures into standard PBR PNG maps
#
# ============================================================

from __future__ import annotations

import math

from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path

from PIL import Image, ImageChops, ImageOps

from app.models.texture_info import TextureInfo


# ============================================================
# Exceptions
# ============================================================


class PBRConversionError(Exception):
    """
    Base exception raised when a texture cannot be converted.
    """


class UnsupportedTextureTypeError(PBRConversionError):
    """
    Raised when the source texture is not recognized as _c, _n or _ao.
    """


class MissingTextureImageError(PBRConversionError):
    """
    Raised when TextureInfo does not contain decoded image data.
    """


class PBRExportError(PBRConversionError):
    """
    Raised when generated maps cannot be written to disk.
    """


# ============================================================
# Conversion types
# ============================================================


class WarThunderTextureType(Enum):
    """
    Supported War Thunder source texture types.
    """

    COLOR = "_c"
    NORMAL = "_n"
    AMBIENT_OCCLUSION = "_ao"


class PBRMapType(Enum):
    """
    PBR maps generated by the converter.
    """

    ALBEDO = "albedo"
    MASK = "mask"
    NORMAL = "normal"
    ROUGHNESS = "roughness"
    METALLIC = "metallic"
    AMBIENT_OCCLUSION = "ao"


# ============================================================
# Conversion models
# ============================================================


@dataclass(slots=True)
class GeneratedPBRMap:
    """
    One image generated from a War Thunder source texture.
    """

    map_type: PBRMapType
    image: Image.Image
    suggested_filename: str
    source_path: Path

    exported_path: Path | None = None

    @property
    def name(self) -> str:
        return self.map_type.value

    @property
    def size(self) -> tuple[int, int]:
        return self.image.size

    @property
    def mode(self) -> str:
        return self.image.mode

    @property
    def was_exported(self) -> bool:
        return self.exported_path is not None


@dataclass(slots=True)
class PBRConversionResult:
    """
    Complete result of converting one source texture.
    """

    source_texture: TextureInfo
    source_path: Path
    source_type: WarThunderTextureType

    maps: list[GeneratedPBRMap] = field(
        default_factory=list
    )

    warnings: list[str] = field(
        default_factory=list
    )

    @property
    def map_count(self) -> int:
        return len(self.maps)

    @property
    def map_types(self) -> list[PBRMapType]:
        return [
            generated_map.map_type
            for generated_map in self.maps
        ]

    @property
    def exported_paths(self) -> list[Path]:
        return [
            generated_map.exported_path
            for generated_map in self.maps
            if generated_map.exported_path is not None
        ]

    def get_map(
        self,
        map_type: PBRMapType,
    ) -> GeneratedPBRMap | None:
        for generated_map in self.maps:
            if generated_map.map_type is map_type:
                return generated_map

        return None

    def has_map(
        self,
        map_type: PBRMapType,
    ) -> bool:
        return self.get_map(map_type) is not None


@dataclass(slots=True)
class PBRBatchConversionResult:
    """
    Result of converting multiple source textures.
    """

    results: list[PBRConversionResult] = field(
        default_factory=list
    )

    errors: list[tuple[Path, str]] = field(
        default_factory=list
    )

    @property
    def converted_texture_count(self) -> int:
        return len(self.results)

    @property
    def generated_map_count(self) -> int:
        return sum(
            result.map_count
            for result in self.results
        )

    @property
    def error_count(self) -> int:
        return len(self.errors)

    @property
    def exported_paths(self) -> list[Path]:
        paths: list[Path] = []

        for result in self.results:
            paths.extend(
                result.exported_paths
            )

        return paths


# ============================================================
# Converter
# ============================================================


class PBRConverter:
    """
    Converts War Thunder textures into standard PBR maps.

    Supported conversions:

        *_c
            RGB   -> Albedo
            Alpha -> Mask, when the source really contains alpha

        *_n
            R     -> inverted Roughness
            B     -> Metallic
            G + A -> reconstructed RGB Normal map

        *_ao
            RGB   -> Ambient Occlusion

    The converter performs no user-interface operations.
    """

    PNG_EXTENSION = ".png"

    # Normal-map reconstruction options.
    #
    # War Thunder stores two normal components in the G and Alpha
    # channels of the _n texture. These values are interpreted as
    # unsigned normalized vector components.
    NORMAL_X_SOURCE = "alpha"
    NORMAL_Y_SOURCE = "green"

    def convert_texture(
        self,
        texture: TextureInfo,
    ) -> PBRConversionResult:
        """
        Converts one TextureInfo object into PBR maps.
        """

        self._validate_texture(texture)

        source_path = self._get_source_path(
            texture
        )

        source_type = self.detect_texture_type_from_texture(
            texture
        )

        source_image = self._get_source_image(
            texture
        )

        base_name = self._get_base_name(
            source_path,
            source_type,
        )

        if source_type is WarThunderTextureType.COLOR:
            return self._convert_color_texture(
                texture=texture,
                source_path=source_path,
                source_image=source_image,
                base_name=base_name,
            )

        if source_type is WarThunderTextureType.NORMAL:
            return self._convert_normal_texture(
                texture=texture,
                source_path=source_path,
                source_image=source_image,
                base_name=base_name,
            )

        if (
            source_type
            is WarThunderTextureType.AMBIENT_OCCLUSION
        ):
            return self._convert_ao_texture(
                texture=texture,
                source_path=source_path,
                source_image=source_image,
                base_name=base_name,
            )

        raise UnsupportedTextureTypeError(
            f"Unsupported texture type: {source_path.name}"
        )

    def convert_many(
        self,
        textures: list[TextureInfo],
    ) -> PBRBatchConversionResult:
        """
        Converts multiple textures.

        A failed texture does not interrupt conversion of the remaining
        textures.
        """

        batch_result = PBRBatchConversionResult()

        for texture in textures:
            try:
                result = self.convert_texture(
                    texture
                )

                batch_result.results.append(
                    result
                )

            except Exception as error:
                source_path = self._safe_source_path(
                    texture
                )

                batch_result.errors.append(
                    (
                        source_path,
                        str(error),
                    )
                )

        return batch_result

    # ========================================================
    # Export
    # ========================================================

    def export_result(
        self,
        result: PBRConversionResult,
        output_directory: str | Path,
        *,
        overwrite: bool = True,
        normal_map_opengl: bool = False,
    ) -> list[Path]:
        """
        Exports all generated maps from one conversion result as PNG.
        """

        output_path = Path(
            output_directory
        ).expanduser()

        try:
            output_path.mkdir(
                parents=True,
                exist_ok=True,
            )

        except OSError as error:
            raise PBRExportError(
                f"Could not create export directory: "
                f"{output_path}"
            ) from error

        exported_paths: list[Path] = []

        for generated_map in result.maps:
            file_path = (
                output_path
                / generated_map.suggested_filename
            )

            if file_path.exists() and not overwrite:
                raise PBRExportError(
                    f"File already exists: {file_path}"
                )

            image_to_save = generated_map.image

            if (
                normal_map_opengl
                and generated_map.map_type is PBRMapType.NORMAL
            ):
                image_to_save = self._invert_normal_y(
                    image_to_save
                )

            try:
                image_to_save.save(
                    file_path,
                    format="PNG",
                )

            except Exception as error:
                raise PBRExportError(
                    f"Could not export: {file_path}"
                ) from error

            generated_map.exported_path = (
                file_path
            )

            exported_paths.append(
                file_path
            )

        return exported_paths

    def export_batch(
        self,
        batch_result: PBRBatchConversionResult,
        output_directory: str | Path,
        *,
        overwrite: bool = True,
        normal_map_opengl: bool = False,
    ) -> list[Path]:
        """
        Exports every successful conversion result in a batch.
        """

        exported_paths: list[Path] = []

        for result in batch_result.results:
            exported_paths.extend(
                self.export_result(
                    result,
                    output_directory,
                    overwrite=overwrite,
                    normal_map_opengl=normal_map_opengl,
                )
            )

        return exported_paths

    def convert_and_export(
        self,
        textures: list[TextureInfo],
        output_directory: str | Path,
        *,
        overwrite: bool = True,
        normal_map_opengl: bool = False,
    ) -> PBRBatchConversionResult:
        """
        Converts and exports multiple textures.
        """

        batch_result = self.convert_many(
            textures
        )

        for result in batch_result.results:
            try:
                self.export_result(
                    result,
                    output_directory,
                    overwrite=overwrite,
                    normal_map_opengl=normal_map_opengl,
                )

            except Exception as error:
                batch_result.errors.append(
                    (
                        result.source_path,
                        str(error),
                    )
                )

        return batch_result

    @staticmethod
    def _invert_normal_y(
        image: Image.Image,
    ) -> Image.Image:
        """Return an RGB normal map with only its Y/green channel inverted."""
        normal = image.convert("RGB")
        normal_x, normal_y, normal_z = normal.split()
        return Image.merge(
            "RGB",
            (
                normal_x,
                ImageChops.invert(normal_y),
                normal_z,
            ),
        )

    # ========================================================
    # Texture type resolution
    # ========================================================

    def detect_texture_type_from_texture(
        self,
        texture: TextureInfo,
    ) -> WarThunderTextureType:
        """
        Resolves the source role used by conversion.

        Priority:

            1. TextureInfo.effective_type
               (manual override when present, detected role otherwise)
            2. Explicit TextureInfo.manual_type compatibility property
            3. TextureInfo.detected_type compatibility property
            4. Filename suffix fallback
        """

        role_candidates = (
            getattr(
                texture,
                "effective_type",
                None,
            ),
            getattr(
                texture,
                "manual_type",
                None,
            ),
            getattr(
                texture,
                "detected_type",
                None,
            ),
            getattr(
                texture,
                "texture_type",
                None,
            ),
        )

        for role in role_candidates:
            resolved_type = (
                self._map_texture_role(
                    role
                )
            )

            if resolved_type is not None:
                return resolved_type

        return self.detect_texture_type(
            self._get_source_path(
                texture
            )
        )

    @staticmethod
    def _map_texture_role(
        role,
    ) -> WarThunderTextureType | None:
        """
        Maps TextureType enums, compatible enums, and strings to the
        converter's internal WarThunderTextureType.
        """

        if role is None:
            return None

        role_name = getattr(
            role,
            "name",
            None,
        )

        role_value = getattr(
            role,
            "value",
            None,
        )

        candidates = [
            role_name,
            role_value,
            str(role),
        ]

        normalized_values = {
            PBRConverter._normalize_role_name(
                candidate
            )
            for candidate in candidates
            if candidate is not None
        }

        if normalized_values & {
            "COLOR",
            "COLOUR",
            "ALBEDO",
            "BASE_COLOR",
            "BASE_COLOUR",
            "C",
            "_C",
            "TEXTURETYPE_COLOR",
        }:
            return WarThunderTextureType.COLOR

        if normalized_values & {
            "NORMAL",
            "NORMAL_MAP",
            "PACKED_NORMAL",
            "N",
            "_N",
            "TEXTURETYPE_NORMAL",
        }:
            return WarThunderTextureType.NORMAL

        if normalized_values & {
            "AO",
            "AMBIENT_OCCLUSION",
            "OCCLUSION",
            "_AO",
            "TEXTURETYPE_AO",
        }:
            return (
                WarThunderTextureType.AMBIENT_OCCLUSION
            )

        if normalized_values & {
            "IGNORE",
            "IGNORED",
            "SKIP",
            "DISABLED",
            "TEXTURETYPE_IGNORE",
        }:
            raise UnsupportedTextureTypeError(
                "The texture is marked as IGNORE."
            )

        return None

    @staticmethod
    def _normalize_role_name(
        value,
    ) -> str:
        normalized = (
            str(value)
            .strip()
            .upper()
            .replace(" ", "_")
            .replace("-", "_")
            .replace(".", "_")
        )

        while "__" in normalized:
            normalized = normalized.replace(
                "__",
                "_",
            )

        return normalized

    @staticmethod
    def detect_texture_type(
        source_path: str | Path,
    ) -> WarThunderTextureType:
        """
        Detects the War Thunder texture type from its filename suffix.
        """

        path = Path(source_path)
        stem = path.stem.casefold()

        if stem.endswith("_ao"):
            return (
                WarThunderTextureType.AMBIENT_OCCLUSION
            )

        if stem.endswith("_c"):
            return WarThunderTextureType.COLOR

        if stem.endswith("_n"):
            return WarThunderTextureType.NORMAL

        raise UnsupportedTextureTypeError(
            "No manual or automatic texture role was available, and "
            "the filename does not end with '_c', '_n' or '_ao': "
            f"{path.name}"
        )

    @staticmethod
    def _get_base_name(
        source_path: Path,
        source_type: WarThunderTextureType,
    ) -> str:
        """
        Removes a War Thunder suffix only when it is actually present.
        """

        stem = source_path.stem
        expected_suffix = (
            source_type.value.casefold()
        )

        if stem.casefold().endswith(
            expected_suffix
        ):
            stem = stem[
                :-len(expected_suffix)
            ]

        stem = stem.rstrip("_ ")

        return stem or source_path.stem

    # ========================================================
    # _c conversion
    # ========================================================

    def _convert_color_texture(
        self,
        *,
        texture: TextureInfo,
        source_path: Path,
        source_image: Image.Image,
        base_name: str,
    ) -> PBRConversionResult:
        """
        Converts a War Thunder _c texture.

        RGB becomes Albedo.
        Alpha becomes a separate grayscale Mask.
        """

        result = PBRConversionResult(
            source_texture=texture,
            source_path=source_path,
            source_type=WarThunderTextureType.COLOR,
        )

        had_alpha = self._image_has_alpha(
            source_image
        )

        rgba_image = source_image.convert(
            "RGBA"
        )

        red, green, blue, alpha = (
            rgba_image.split()
        )

        albedo_image = Image.merge(
            "RGB",
            (
                red,
                green,
                blue,
            ),
        )

        result.maps.append(
            GeneratedPBRMap(
                map_type=PBRMapType.ALBEDO,
                image=albedo_image,
                suggested_filename=(
                    f"{base_name}_albedo.png"
                ),
                source_path=source_path,
            )
        )

        if had_alpha:
            result.maps.append(
                GeneratedPBRMap(
                    map_type=PBRMapType.MASK,
                    image=alpha.copy(),
                    suggested_filename=(
                        f"{base_name}_mask.png"
                    ),
                    source_path=source_path,
                )
            )

        else:
            result.warnings.append(
                "The source _c texture does not contain "
                "an alpha channel. No mask was generated."
            )

        return result

    # ========================================================
    # _n conversion
    # ========================================================

    def _convert_normal_texture(
        self,
        *,
        texture: TextureInfo,
        source_path: Path,
        source_image: Image.Image,
        base_name: str,
    ) -> PBRConversionResult:
        """
        Converts a War Thunder _n texture.

        Source channel layout:

            R     -> roughness, inverted during conversion
            G     -> one normal-vector component
            B     -> metallic
            Alpha -> second normal-vector component
        """

        result = PBRConversionResult(
            source_texture=texture,
            source_path=source_path,
            source_type=WarThunderTextureType.NORMAL,
        )

        had_alpha = self._image_has_alpha(
            source_image
        )

        rgba_image = source_image.convert(
            "RGBA"
        )

        red, green, blue, alpha = (
            rgba_image.split()
        )

        roughness_image = ImageOps.invert(
            red
        )

        metallic_image = blue.copy()

        result.maps.append(
            GeneratedPBRMap(
                map_type=PBRMapType.ROUGHNESS,
                image=roughness_image,
                suggested_filename=(
                    f"{base_name}_roughness.png"
                ),
                source_path=source_path,
            )
        )

        result.maps.append(
            GeneratedPBRMap(
                map_type=PBRMapType.METALLIC,
                image=metallic_image,
                suggested_filename=(
                    f"{base_name}_metallic.png"
                ),
                source_path=source_path,
            )
        )

        if had_alpha:
            normal_image = (
                self._reconstruct_normal_map(
                    green_channel=green,
                    alpha_channel=alpha,
                )
            )

            result.maps.append(
                GeneratedPBRMap(
                    map_type=PBRMapType.NORMAL,
                    image=normal_image,
                    suggested_filename=(
                        f"{base_name}_normal.png"
                    ),
                    source_path=source_path,
                )
            )

        else:
            result.warnings.append(
                "The source _n texture does not contain "
                "an alpha channel. The normal map could "
                "not be reconstructed."
            )

        return result

    @staticmethod
    def _reconstruct_normal_map(
        *,
        green_channel: Image.Image,
        alpha_channel: Image.Image,
    ) -> Image.Image:
        """
        Reconstructs an RGB tangent-space normal map.

        Current channel interpretation:

            X = source Alpha
            Y = source Green
            Z = reconstructed

        Source X and Y values are converted from the unsigned 0..255
        range into signed -1..1 vector components.

        Z is reconstructed using:

            Z = sqrt(max(0, 1 - X² - Y²))

        The resulting X, Y and Z components are converted back into
        unsigned RGB channels.
        """

        green = green_channel.convert(
            "L"
        )

        alpha = alpha_channel.convert(
            "L"
        )

        if green.size != alpha.size:
            raise PBRConversionError(
                "Normal-map source channels have "
                "different dimensions."
            )

        width, height = green.size

        green_data = green.tobytes()
        alpha_data = alpha.tobytes()

        red_output = bytearray(
            width * height
        )

        green_output = bytearray(
            width * height
        )

        blue_output = bytearray(
            width * height
        )

        for index, (
            green_value,
            alpha_value,
        ) in enumerate(
            zip(
                green_data,
                alpha_data,
            )
        ):
            normal_x = (
                alpha_value / 255.0
            ) * 2.0 - 1.0

            normal_y = (
                green_value / 255.0
            ) * 2.0 - 1.0

            vector_length_squared = (
                normal_x * normal_x
                + normal_y * normal_y
            )

            if vector_length_squared > 1.0:
                vector_length = math.sqrt(
                    vector_length_squared
                )

                normal_x /= vector_length
                normal_y /= vector_length

                normal_z = 0.0

            else:
                normal_z = math.sqrt(
                    max(
                        0.0,
                        1.0
                        - vector_length_squared,
                    )
                )

            red_output[index] = (
                PBRConverter._signed_normal_to_byte(
                    normal_x
                )
            )

            green_output[index] = (
                PBRConverter._signed_normal_to_byte(
                    normal_y
                )
            )

            blue_output[index] = (
                PBRConverter._signed_normal_to_byte(
                    normal_z
                )
            )

        red_image = Image.frombytes(
            "L",
            (width, height),
            bytes(red_output),
        )

        green_image = Image.frombytes(
            "L",
            (width, height),
            bytes(green_output),
        )

        blue_image = Image.frombytes(
            "L",
            (width, height),
            bytes(blue_output),
        )

        return Image.merge(
            "RGB",
            (
                red_image,
                green_image,
                blue_image,
            ),
        )

    @staticmethod
    def _signed_normal_to_byte(
        value: float,
    ) -> int:
        clamped_value = max(
            -1.0,
            min(
                1.0,
                value,
            ),
        )

        unsigned_value = (
            clamped_value * 0.5 + 0.5
        )

        return max(
            0,
            min(
                255,
                round(
                    unsigned_value * 255.0
                ),
            ),
        )

    # ========================================================
    # _ao conversion
    # ========================================================

    def _convert_ao_texture(
        self,
        *,
        texture: TextureInfo,
        source_path: Path,
        source_image: Image.Image,
        base_name: str,
    ) -> PBRConversionResult:
        """
        Converts a War Thunder _ao texture.

        The source RGB data remains one RGB Ambient Occlusion image.
        """

        result = PBRConversionResult(
            source_texture=texture,
            source_path=source_path,
            source_type=(
                WarThunderTextureType.AMBIENT_OCCLUSION
            ),
        )

        ao_image = source_image.convert(
            "RGB"
        )

        result.maps.append(
            GeneratedPBRMap(
                map_type=PBRMapType.AMBIENT_OCCLUSION,
                image=ao_image,
                suggested_filename=(
                    f"{base_name}_ao.png"
                ),
                source_path=source_path,
            )
        )

        return result

    # ========================================================
    # Validation and image access
    # ========================================================

    @staticmethod
    def _validate_texture(
        texture: TextureInfo,
    ) -> None:
        if not isinstance(
            texture,
            TextureInfo,
        ):
            raise TypeError(
                "PBRConverter accepts only "
                "TextureInfo objects."
            )

    @staticmethod
    def _get_source_path(
        texture: TextureInfo,
    ) -> Path:
        try:
            return Path(
                texture.file.path
            )

        except Exception as error:
            raise PBRConversionError(
                "TextureInfo does not contain "
                "a valid source path."
            ) from error

    @staticmethod
    def _safe_source_path(
        texture: TextureInfo,
    ) -> Path:
        try:
            return Path(
                texture.file.path
            )

        except Exception:
            return Path(
                "<unknown texture>"
            )

    @staticmethod
    def _get_source_image(
        texture: TextureInfo,
    ) -> Image.Image:
        """
        Retrieves the decoded Pillow image from TextureInfo.

        The current compatibility alias texture.image is used first.
        A fallback to texture.preview.image is included for future model
        changes.
        """

        image = getattr(
            texture,
            "image",
            None,
        )

        if isinstance(
            image,
            Image.Image,
        ):
            return image

        preview = getattr(
            texture,
            "preview",
            None,
        )

        if preview is not None:
            preview_image = getattr(
                preview,
                "image",
                None,
            )

            if isinstance(
                preview_image,
                Image.Image,
            ):
                return preview_image

        raise MissingTextureImageError(
            "The texture does not contain decoded image data. "
            "Its format or compression may not currently support "
            "Pillow preview and PBR conversion."
        )

    @staticmethod
    def _image_has_alpha(
        image: Image.Image,
    ) -> bool:
        """
        Checks whether the original image contains a real alpha channel.

        Converting an RGB image to RGBA automatically creates opaque
        alpha, so the check must happen before conversion.
        """

        if image.mode in {
            "RGBA",
            "LA",
            "PA",
        }:
            return True

        if image.mode == "P":
            transparency = image.info.get(
                "transparency"
            )

            return transparency is not None

        return (
            "A"
            in image.getbands()
        )